# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 17:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Economy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean', models.BooleanField(default=False)),
                ('open', models.BooleanField(default=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Economy.Employee')),
            ],
            options={
                'verbose_name': 'Golv',
                'verbose_name_plural': 'Golven',
            },
        ),
        migrations.CreateModel(
            name='Freezer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Typ av frys')),
                ('location', models.CharField(max_length=255, verbose_name='Plats')),
                ('active', models.BooleanField(default=True, verbose_name='Är den aktiv?')),
            ],
            options={
                'verbose_name': 'Frys',
                'ordering': ['-active'],
                'verbose_name_plural': 'Frysar',
            },
        ),
        migrations.CreateModel(
            name='FreezerTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured', models.IntegerField(verbose_name='Uppmätt temperatur')),
                ('defrosted', models.BooleanField(default=False, verbose_name='Avfrostad')),
                ('anomaly', models.BooleanField(default=False, verbose_name='avvikelse')),
                ('cleaned', models.BooleanField(verbose_name='Städat')),
                ('comment', models.TextField(blank=True, max_length=255, verbose_name='kommentar')),
                ('prescribedMaxTempFridge', models.PositiveIntegerField(default=8)),
                ('prescribedMinTempFridge', models.PositiveIntegerField(default=4)),
                ('prescribedMaxTempFreezer', models.IntegerField(default=-4)),
                ('prescribedMinTempFreezer', models.IntegerField(default=-20)),
                ('date', models.DateField(default=datetime.date.today)),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Economy.Employee', verbose_name='Signatur')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cleaning.Freezer', verbose_name='Typ av frys')),
            ],
            options={
                'verbose_name': 'Kontrollpunkt frys',
                'ordering': ['-date'],
                'verbose_name_plural': 'Kontrollpunkter frysar',
            },
        ),
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Typ av kyl')),
                ('location', models.CharField(max_length=255, verbose_name='Plats')),
                ('active', models.BooleanField(default=True, verbose_name='Är den aktiv?')),
            ],
            options={
                'verbose_name': 'Kyl',
                'ordering': ['-active'],
                'verbose_name_plural': 'Kylar',
            },
        ),
        migrations.CreateModel(
            name='FridgeTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured', models.IntegerField(verbose_name='Uppmätt temperatur')),
                ('defrosted', models.BooleanField(default=False, verbose_name='Avfrostad')),
                ('anomaly', models.BooleanField(default=False, verbose_name='avvikelse')),
                ('cleaned', models.BooleanField(verbose_name='Städat')),
                ('comment', models.TextField(blank=True, max_length=255, verbose_name='kommentar')),
                ('prescribedMaxTempFridge', models.PositiveIntegerField(default=8)),
                ('prescribedMinTempFridge', models.PositiveIntegerField(default=4)),
                ('prescribedMaxTempFreezer', models.IntegerField(default=-4)),
                ('prescribedMinTempFreezer', models.IntegerField(default=-20)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='datum')),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Economy.Employee', verbose_name='Signatur')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cleaning.Fridge', verbose_name='Enhet')),
            ],
            options={
                'verbose_name': 'Kontrollpunkt kylskåp',
                'ordering': ['date'],
                'verbose_name_plural': 'Kontrollpunkter kylskåp',
            },
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean', models.BooleanField(default=False)),
                ('open', models.BooleanField(default=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Economy.Employee')),
            ],
            options={
                'verbose_name': 'Köket',
            },
        ),
    ]
