# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-18 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clean',
            name='anomaly',
            field=models.BooleanField(default=False, verbose_name='Avvikelse'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='anomaly',
            field=models.BooleanField(default=False, verbose_name='Avvikelse'),
        ),
        migrations.AddField(
            model_name='facilitydamage',
            name='anomaly',
            field=models.BooleanField(default=False, verbose_name='Avvikelse'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='anomaly',
            field=models.BooleanField(default=False, verbose_name='Avvikelse'),
        ),
    ]
