# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-10 20:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Economy', '0001_initial'),
        ('cleaning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('recepie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production', to='cleaning.Recepie')),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signature', to='Economy.Employee')),
            ],
        ),
    ]
