# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-18 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0002_auto_20170518_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
