# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-18 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0004_auto_20170518_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coldstorage',
            options={'verbose_name': 'kontrollpunk - Temperatur', 'verbose_name_plural': 'kontrollpunkter - Temperatur'},
        ),
        migrations.AlterField(
            model_name='coldstorage',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='control_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cleaning.ColdStorage', verbose_name='Kontrollpunkt'),
        ),
    ]
