# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-18 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0005_auto_20170518_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clean',
            name='control_point',
        ),
        migrations.RemoveField(
            model_name='clean',
            name='signature',
        ),
    ]
