# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-19 14:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Economy', '0001_initial'),
        ('cleaning', '0007_auto_20170519_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Datum')),
                ('anomaly', models.BooleanField(default=False, verbose_name='Avvikelse')),
                ('measure', models.CharField(blank=True, help_text='Vilken åtgärd har tagits?', max_length=100, verbose_name='Åtgärd')),
                ('comment', models.TextField(blank=True, max_length=255, verbose_name='kommentar')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cleaned', models.BooleanField(default=False, verbose_name='Städat?')),
                ('control_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cleaning.ControlPoint', verbose_name='Kontrollpunkt')),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Economy.Employee', verbose_name='signatur')),
            ],
            options={
                'verbose_name': 'Dokumentera städning',
                'verbose_name_plural': 'Dokumentera städning',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Datum')),
                ('anomaly', models.BooleanField(default=False, verbose_name='Avvikelse')),
                ('measure', models.CharField(blank=True, help_text='Vilken åtgärd har tagits?', max_length=100, verbose_name='Åtgärd')),
                ('comment', models.TextField(blank=True, max_length=255, verbose_name='kommentar')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('smell', models.BooleanField(default=True, verbose_name='Lukt ok?')),
                ('damaged', models.BooleanField(default=False, verbose_name='Förpackning ok?')),
                ('expired', models.BooleanField(default=False, verbose_name='Datum ok?')),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Economy.Employee', verbose_name='signatur')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cleaning.Supplier', verbose_name='Leverantör')),
            ],
            options={
                'verbose_name': 'Dokumentera leverans',
                'ordering': ['date'],
                'verbose_name_plural': 'Dokumentera leveranser',
            },
        ),
        migrations.CreateModel(
            name='FacilityDamage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Datum')),
                ('anomaly', models.BooleanField(default=False, verbose_name='Avvikelse')),
                ('measure', models.CharField(blank=True, help_text='Vilken åtgärd har tagits?', max_length=100, verbose_name='Åtgärd')),
                ('comment', models.TextField(blank=True, max_length=255, verbose_name='kommentar')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('repaired', models.BooleanField(default=False, verbose_name='Reparerad?')),
                ('location', models.TextField(max_length=100, verbose_name='Plats')),
                ('description', models.TextField(max_length=500, verbose_name='Beskrivning')),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Economy.Employee', verbose_name='signatur')),
            ],
            options={
                'verbose_name': 'Dokumentera fastighetsskada',
                'verbose_name_plural': 'Dokumentera fastighetsskador',
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Datum')),
                ('anomaly', models.BooleanField(default=False, verbose_name='Avvikelse')),
                ('measure', models.CharField(blank=True, help_text='Vilken åtgärd har tagits?', max_length=100, verbose_name='Åtgärd')),
                ('comment', models.TextField(blank=True, max_length=255, verbose_name='kommentar')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('measured', models.IntegerField(verbose_name='Uppmätt temperatur')),
                ('control_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cleaning.ColdStorage', verbose_name='Kontrollpunkt')),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Economy.Employee', verbose_name='signatur')),
            ],
            options={
                'verbose_name': 'dokumentera temperatur',
                'ordering': ['date'],
                'verbose_name_plural': 'dokumentera temperaturer',
            },
        ),
    ]
