# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-19 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0008_clean_delivery_facilitydamage_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazard',
            name='routine',
        ),
        migrations.RemoveField(
            model_name='hazard',
            name='routine_sufficient',
        ),
        migrations.AddField(
            model_name='controlpoint',
            name='routine_sufficient',
            field=models.BooleanField(default=True),
        ),
    ]
