# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-10 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('text', models.TextField(max_length=2000)),
                ('image', models.ImageField(upload_to='static/img/events')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pub_start', models.DateField()),
                ('pub_end', models.DateField()),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Evenemang',
                'ordering': ('-published',),
            },
        ),
    ]
