# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-10 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_imagealt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='/media/img/'),
        ),
    ]
