# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170426_2157'),
        ('events', '0004_auto_20170425_0856'),
    ]

    operations = [
    ]
