# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 22:46
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_merge_20170426_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=2000),
        ),
    ]
