# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-29 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170426_2246'),
        ('events', '0005_merge_20170426_2219'),
    ]

    operations = [
    ]
