# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_merge_20170426_2219'),
        ('events', '0006_auto_20170426_2246'),
    ]

    operations = [
    ]
