# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-04 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_merge_20170427_1155'),
        ('events', '0007_merge_20170429_1310'),
    ]

    operations = [
    ]
