# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-01 11:09
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('short_description', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('message', ckeditor.fields.RichTextField(max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img/uploads/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'epost-meddelanden',
                'verbose_name': 'epost-meddelande',
            },
        ),
    ]
