# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-01 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtexts',
            old_name='message',
            new_name='html_message',
        ),
        migrations.AddField(
            model_name='emailtexts',
            name='plain_text',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
