# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 17:12
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20170501_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='identifying slug for page, e.g., "meny"')),
            ],
            options={
                'verbose_name': 'sida',
                'verbose_name_plural': 'sidor',
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(help_text='ex. kaffe', max_length=30)),
                ('text', ckeditor.fields.RichTextField(max_length=2000)),
                ('image', models.ImageField(blank=True, upload_to='static/img/uploads/')),
                ('publish', models.BooleanField(default=False)),
                ('page', models.ForeignKey(blank=True, help_text='På vilken sida vill du publicera detta?', on_delete=django.db.models.deletion.PROTECT, to='docs.Page')),
            ],
            options={
                'verbose_name': 'sidinnehåll',
                'verbose_name_plural': 'sidinnehåll',
                'ordering': ['-publish', 'page', 'shortname'],
            },
        ),
    ]
