# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 18:14
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_page_pagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='headline',
            field=models.CharField(default='', help_text='H1-rubrik', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='ingress',
            field=ckeditor.fields.RichTextField(default='', help_text='kort ingress, max 500 tecken', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='headline',
            field=models.CharField(default='', help_text='kort H2-rubrik, ex "riktigt gott kaffe"', max_length=100),
            preserve_default=False,
        ),
    ]
