# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_auto_20170505_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default='', help_text='sidans titel', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='image_alt',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
