# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_auto_20170505_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
