# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-06 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_auto_20170505_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='image',
            field=models.ImageField(blank=True, upload_to='/static/img/uploads/'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='image_alt',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
