# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-03 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_auto_20170506_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel', models.BooleanField(default=False, help_text='Ska denna banner finnas med i bildväxlingen på toppen av sidan?', verbose_name='Karusell')),
                ('order', models.PositiveIntegerField(verbose_name='Ordning')),
                ('image', models.ImageField(upload_to='/static/img/uploads/', verbose_name='Bild')),
                ('h1', models.CharField(blank=True, max_length=40, verbose_name='Stor bildtext')),
                ('h3', models.CharField(blank=True, max_length=40, verbose_name='Mindre bildtext')),
                ('page', models.ForeignKey(blank=True, help_text='Vilken sida ska bannern hantera?', on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner', to='docs.Page', verbose_name='Sida')),
            ],
        ),
    ]
