# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-03 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
