# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-05 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0012_auto_20170605_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='static_banner',
            field=models.BooleanField(default=False),
        ),
    ]
