# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-10 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='attribute',
            field=models.CharField(choices=[('adult', 'vuxen'), ('young', 'ungdom'), ('child', 'barn'), ('smallChild', 'småbarn')], max_length=10, verbose_name='vuxen/barn'),
        ),
        migrations.AlterField(
            model_name='bikeavailable',
            name='bike',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='availability', to='database.Bike'),
        ),
    ]
