# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-21 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20170501_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='preliminary',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('cancl', 'Avbokad'), ('actv', 'Aktiv'), ('cmplt', 'Genomförd'), ('prel', 'Preliminär')], default='actv', max_length=5, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
