# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-27 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20170521_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Vilken dag?')),
                ('adult_bike', models.PositiveIntegerField(blank=True, help_text='Antal vuxencyklar')),
                ('child_bike', models.PositiveIntegerField(blank=True, help_text='Antal barncyklar')),
                ('text', models.TextField(max_length=2000)),
                ('image', models.ImageField(blank=True, upload_to='static/img/uploads/')),
                ('image_alt', models.CharField(blank=True, max_length=30)),
                ('distance', models.PositiveIntegerField(blank=True, verbose_name='Hur långt cyklar man?')),
                ('locks', models.PositiveIntegerField(blank=True, verbose_name='Hur många slussar?')),
                ('lunch', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lunch', to='database.Lunch')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='används i URL, använd inte åäö', max_length=30, verbose_name='Internt namn')),
                ('title', models.CharField(max_length=40, verbose_name='Namn på paketet.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Pris exkl. moms')),
                ('vat25', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Moms 25%')),
                ('vat12', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Moms 12%')),
                ('ingress', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='static/img/uploads/')),
                ('image_alt', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Targetgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Namn på målgrupp')),
                ('behaviour', models.TextField(help_text='Hur beter sig målgruppen i övrigt? Ex. Är de aktiva/livsnjutare?', max_length=1000, verbose_name='Beteende')),
                ('values', models.TextField(help_text='Vad har de för värderingar?', max_length=1000, verbose_name='Värderingar')),
                ('buys', models.TextField(max_length=1000, verbose_name='Vad köper de annars?')),
            ],
            options={
                'verbose_name': 'Målgrupp',
                'verbose_name_plural': 'Målgrupper',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.BooleanField(default=False, verbose_name='Paketbokning'),
        ),
        migrations.AlterField(
            model_name='bikesbooking',
            name='bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bike', to='database.Bike'),
        ),
        migrations.AlterField(
            model_name='bikesbooking',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='booked_bike', to='database.Booking'),
        ),
        migrations.AddField(
            model_name='package',
            name='targetgroup',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='targetgroup', to='database.Targetgroup'),
        ),
        migrations.AddField(
            model_name='day',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='days', to='database.Package'),
        ),
        migrations.AddField(
            model_name='day',
            name='room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Rooms'),
        ),
    ]
