# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-28 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20170527_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikesbooking',
            name='booking',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='booked_bike', to='database.Booking'),
        ),
    ]
