# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-05 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20170528_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikesbooking',
            name='out',
            field=models.BooleanField(default=False, verbose_name='Utlämnad'),
        ),
        migrations.AddField(
            model_name='bikesbooking',
            name='returned',
            field=models.BooleanField(default=False, verbose_name='Återlämnad'),
        ),
        migrations.AddField(
            model_name='package',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Är paketet aktivt?'),
        ),
        migrations.AlterField(
            model_name='bikeavailable',
            name='bike',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='availability', to='database.Bike'),
        ),
        migrations.AlterField(
            model_name='bikeavailable',
            name='bookings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='availableBike', to='database.BikesBooking'),
        ),
    ]
