# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-05 20:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20170605_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikesbooking',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(1), '1 Dag'), (datetime.timedelta(2), '2 Dagar'), (datetime.timedelta(3), '3 Dagar'), (datetime.timedelta(4), '4 Dagar'), (datetime.timedelta(5), '5 Dagar'), (datetime.timedelta(6), '6 Dagar'), (datetime.timedelta(7), '7 Dagar')], default=datetime.timedelta(1)),
        ),
        migrations.AlterField(
            model_name='bikesbooking',
            name='to_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
