# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-11 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20170610_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='inlcude_adultbike',
            new_name='include_adultbike',
        ),
        migrations.AddField(
            model_name='day',
            name='dinner',
            field=models.CharField(blank=True, choices=[('menu', 'Smaka på Skaraborg-meny'), ('custom', 'Valfri varmrätt'), ('dinner', 'middag')], max_length=20, verbose_name='Middag'),
        ),
    ]
