# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-17 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20170617_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunch',
            name='type',
        ),
        migrations.AddField(
            model_name='lunch',
            name='internal',
            field=models.CharField(default='', help_text='Namn att använda i koden, ändra inte!!', max_length=15, verbose_name='Internt namn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lunch',
            name='name',
            field=models.CharField(default='', help_text='Namn att visa utåt', max_length=25, verbose_name='Lunch'),
            preserve_default=False,
        ),
    ]
