# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-18 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_lunch_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikesbooking',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bikesbooking',
            name='to_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='type',
            field=models.CharField(blank=True, choices=[(None, 'övrigt'), ('picnic', 'Picknicklunch')], max_length=15, null=True, verbose_name='lunchtyp'),
        ),
    ]
