# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-20 21:07
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20170620_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestprofile',
            options={'verbose_name': 'Gästprofil', 'verbose_name_plural': 'Gästprofiler'},
        ),
        migrations.AlterModelManagers(
            name='guest',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Profil skapad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='email',
            field=models.EmailField(default='adrian.g@telia.com', max_length=254, verbose_name='Epost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='first_name',
            field=models.CharField(default='Adrian', max_length=30, verbose_name='Förnamn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='last_name',
            field=models.CharField(default='Gustafson', max_length=30, verbose_name='Efternamn'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guestprofile',
            name='newsletter',
            field=models.BooleanField(default=True, verbose_name='Nyhetsbrev'),
        ),
        migrations.AlterField(
            model_name='guestprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Telefonnummer'),
        ),
    ]
